version: "3.7"

services:

  browserless:
    image: browserless/chrome:latest
    container_name: "browserless"
    environment:
      - DEBUG=browserless/chrome
      - MAX_CONCURRENT_SESSIONS=100
    ports:
        - 8082:3000